feat: add basic language support to inline CKE editor
oat-sa/ckeditor-dev pull request #29
Opened 2022-07-08 07:06 UTC by meefox

## What is the purpose of this pull request?

## Does your PR contain necessary tests?

All patches that change the editor code must include tests. You can always read more
on [PR testing](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_contributing_code.html#tests),
[how to set the testing environment](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html) and
[how to create tests](https://ckeditor.com/docs/ckeditor4/latest/guide/dev_tests.html#creating-your-own-test)
in the official CKEditor documentation.

### This PR contains

- [ ] Unit tests
- [ ] Manual tests

## Did you follow the CKEditor 4 code style guide?

Your code should follow the guidelines from the [CKEditor 4 code style guide](https://github.com/ckeditor/ckeditor4/blob/major/dev/docs/codestyle.md) which helps keep the entire codebase consistent.

- [ ] PR is consistent with the code style guide

## What is the proposed changelog entry for this pull request?

```
*[#<ISSUE_NUMBER>](https://github.com/ckeditor/ckeditor4/issues/<ISSUE_NUMBER>): Describe the purpose of the pull request in a few simple sentences.
```

## What changes did you make?

*Give an overview…*

## Which issues does your PR resolve?

Closes #<ISSUE_NUMBER>.

Part 4/4

2022-07-08 10:39 UTC, jsconan requested changes
It looks straightforward.
I have a remark though, about the version. Please see the comment below.

2022-07-08 10:39 UTC, jsconan commented on dev/builder/build.sh
> +VERSION="4.15.1 TAO-1"
**issue:** The version of CKE must remain in sync with the base repo.

**suggestion:** I'd rather suggest to increase the TAO version
```suggestion
VERSION="4.14.1 TAO-2"
```

2022-07-12 13:04 UTC, jsconan approved these changes
LGTM

2022-07-13 15:52 UTC, bziondik approved these changes
- [ ]  New code is covered by tests (if applicable)
- [ ]  Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x]  New code is respecting code style rules
- [x]  New code is respecting best practices
- [x]  New code is not subject to concurrency issues (if applicable)
- [x]  Feature is working correctly on my local machine (if applicable)
- [x]  Acceptance criteria are respected
- [x]  Pull request title and description are meaningful

2022-07-20 08:01 UTC, shaveko approved these changes

2022-07-20 10:07 UTC, bziondik approved these changes

2022-07-22 08:58 UTC, merged