Feat/aut 2651/furigana ruby plugin
oat-sa/ckeditor-dev pull request #32
Opened 2022-10-05 14:49 UTC by bziondik

Related to: https://oat-sa.atlassian.net/browse/AUT-2651

**For test use https://github.com/oat-sa/tao-core/pull/3644** 

How to test:
- go to item or passage Authoring
- put interaction or text block
- put text
- select text
- use furigana plugin
- save item

<img width="497" alt="image" src="https://user-images.githubusercontent.com/25976342/195860294-fa0ea9c2-a9ad-4c54-9c67-3cb878855494.png">

2022-11-08 13:59 UTC, marpesia approved these changes
LGTM

2022-11-09 09:26 UTC, Silvia-loza approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [X] New code is respecting code style rules
- [X] New code is respecting best practices
- [X]  Pull request's target is not` master`
- [ ] Feature is working correctly on my local machine (if applicable)
- [X] Feature is working correctly on kitchen env. (if applicable)
- [X] Acceptance criteria are respected
- [X] Pull request title and description are meaningful

2022-11-18 08:23 UTC, marpesia commented on plugins/taofurigana/plugin.js
> +					console.log('rubyElement ', rubyElement);
Please, remove the console.log

2022-11-18 09:17 UTC, marpesia commented on plugins/taofurigana/plugin.js
> +					console.log('rubyElement ', rubyElement);
Please remove the consoles
![image](https://user-images.githubusercontent.com/11692751/202666178-a8536cda-3ad6-48c3-af4d-2092a251dc8f.png)

2022-11-18 09:41 UTC, marpesia requested changes
Pending the console.log remove

2022-11-18 10:31 UTC, marpesia approved these changes
LGTM

2022-11-24 07:53 UTC, merged